# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EasyTipViewGit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'EasyTipView', '~> 2.1'

  # Pods for EasyTipViewGit

end
